language: csharp
mono: none
dotnet: 2.1.2
cache:
  directories:
  - $HOME/.nuget/packages
before_install:
  - eval "$(curl -Ss https://raw.githubusercontent.com/neovim/bot-ci/master/scripts/travis-setup.sh) nightly-x64"
script:
  - dotnet run --project
    src/NvimClient.APIGenerator/NvimClient.APIGenerator.csproj
    src/NvimClient.API/NvimAPI.generated.cs
  - dotnet build
  - dotnet test test/NvimClient.Test/NvimClient.Test.csproj
